Fixed help, added output redirection

diff --git a/ff-lapse b/ff-lapse
--- a/ff-lapse
+++ b/ff-lapse
@@ -7,41 +7,50 @@ options:
 	-n PATH			File used to store temporal variables (default=/tmp/ff-lapse)
 	-s WIDTHxHEIGHT	Dimensions in pixels of the image captured by the device (default=1920x1080)
 	-m N > 9		Max number of images to take into accout for zero padding (default=10^(10))
-	-t N > 0		Time between shots in seconds (default=1)'
+	-t N > 0		Time between $out in seconds (default=1)'
 
 tmp="/tmp/ff-lapse"
 dev="/dev/video0"
 size="1920x1080"
 time=1
 max="10000000000"
+out="shots/"
 
-while getopts 't:m:n:d:s:' OPTION
+while getopts 'o:t:m:n:d:s:h' OPTION
 do
 	case "$OPTION" in
 		d)			
-			[ -z $OPTARG ] && { echo $h; exit 0; }
+			[ -z $OPTARG ] && { echo "$h" >&2; exit 0; }
 			ls $OPTARG &> /dev/null && dev=$OPTARG || { echo "ERROR: $OPTARG does not exist. Exiting."; exit 0; }
 			;;
 		n)
-			[ -n $OPTARG ] && { echo $h; exit 0; }
+			[ -z $OPTARG ] && { echo "$h" >&2; exit 0; }
 			tmp=$OPTARG
 			;;
 		s)
-			[ -n $OPTARG ] && { echo $h; exit 0; }
+			[ -z $OPTARG ] && { echo "$h" >&2; exit 0; }
 			size=$OPTARG
 			;;
 		m)
-			[ -n $OPTARG ] && { echo $h; exit 0; }
-			echo $OPTARG | egrep -q '^[0-9]+$' && [ $OPTARG -gt 9 ] || { echo $h; exit 0; }
+			[ -z $OPTARG ] && { echo "$h" >&2; exit 0; }
+			echo $OPTARG | egrep -q '^[0-9]+$' && [ $OPTARG -gt 9 ] || { echo "$h" >&2; exit 0; }
 			max=$OPTARG
 			;;
 		t)
-			[ -n $OPTARG ] && { echo $h; exit 0; }
-			echo $OPTARG | egrep -q '^[0-9]+$' && [ $OPTARG -gt 0 ] || { echo $h; exit 0; }
+			[ -z $OPTARG ] && { echo "$h" >&2; exit 0; }
+			echo $OPTARG | egrep -q '^[0-9]+$' && [ $OPTARG -gt 0 ] || { echo "$h" >&2; exit 0; }
 			time=$OPTARG
 			;;
+		o)
+		 	[ -z $OPTARG ] && { echo "$h" >&2; exit 0; }
+			out=$OPTARG
+			;;
+		h)  
+			echo "$h" >&2
+			exit 0
+			;;
 		?)
-			echo $h
+			echo "$h" >&2
 			exit 0
 			;;
 	esac
@@ -49,7 +58,7 @@ done
 			
 			
 
-mkdir shots &> /dev/null || [ -z "`ls shots 2> /dev/null`" ] || { echo "'shots' folder is not empty. Do you want to clear all its contents PERMANENTLY [y/N]?" && { read y && { [ $y == "y" ] &> /dev/null && rm -rf shots/* || { echo "Folder could not be cleared, exiting..."; exit 0;}; }; }; }
+mkdir -p $out && { [ -z "`ls $out`" ] || { echo "'$out' folder is not empty. Do you want to clear all its contents PERMANENTLY [y/N]?" && { read y && { [ $y == "y" ] && rm -r $out/* || { echo "Folder could not be cleared, exiting..."; exit 0;}; }; }; };} || { echo "Error creating directory '$out', exiting..."; exit 0; }
 
 pad=$(($max-1))
 pad=${#pad}
@@ -59,7 +68,7 @@ echo 0 > $tmp
 cmd="$cmd read N < $tmp;"
 cmd="$cmd N="'$(echo $N | sed 's/^0*//')'";"
 cmd="$cmd ffmpeg -f v4l2 -video_size $size -i $dev -vframes 1"
-cmd="$cmd ""shots/"'shot$(printf "%0'"$pad"'d" $N)'".jpeg;"
+cmd="$cmd ""$out/"'shot$(printf "%0'"$pad"'d" $N)'".jpeg;"
 cmd="$cmd "'N=$((N+1));'
 cmd="$cmd echo"' $N > '"$tmp"
 
